/*
 * W projekcie wykorzystana została biblioteka JUNG - http://jung.sourceforge.net/,
 * która jest open-source na licencji BSD
 * 
 */
package smip;

import factory.EdgeFactory;
import Struktura_jung.Przerob;
import factory.CircVertexFactory;
import Struktura_jung.lokator;
import Struktura_jung.node;
import edu.uci.ics.jung.algorithms.layout.CircleLayout;
import edu.uci.ics.jung.algorithms.layout.FRLayout;
import edu.uci.ics.jung.algorithms.layout.ISOMLayout;
import edu.uci.ics.jung.algorithms.layout.KKLayout;
import edu.uci.ics.jung.algorithms.layout.SpringLayout;
import edu.uci.ics.jung.algorithms.layout.StaticLayout;
import edu.uci.ics.jung.graph.DirectedSparseGraph;
import edu.uci.ics.jung.visualization.VisualizationViewer;
import edu.uci.ics.jung.visualization.control.DefaultModalGraphMouse;
import edu.uci.ics.jung.visualization.control.EditingGraphMousePlugin;
import edu.uci.ics.jung.visualization.control.GraphMouseListener;
import edu.uci.ics.jung.visualization.control.ModalGraphMouse;
import edu.uci.ics.jung.visualization.control.PluggableGraphMouse;
import factory.RectVertexFactory;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import javax.swing.JFrame;
import javax.swing.JMenu;
import model.nodeShape;




public class MainGUI extends javax.swing.JFrame{




    //public parametryGrafowe u;
    public JMenu myszmenu;
    DefaultModalGraphMouse mysz;
    public int i=1;
    BufferedImage bi;
    Thread t;
    public float[] tab;
    public int pom=0;
 //   DefaultXYItemRenderer re;
  //  StandardTickUnitSource ts;
    /////////////////
   public boolean flaga=false;
   public int najgorszy=0;//najgorszy w pokoleniu
   public boolean flaga_zly=false;//flaga do powyzej
   public int naj_pok=0;//najlepszy w pokoleniu
   public boolean flaga_n_pok=false;//flaga do tego
   public boolean koniec=false;
   public boolean flaga_mediana;
   public int mediana;
   VisualizationViewer<node, Integer> vv=null;
   public DirectedSparseGraph<node,Integer> graf_jung=null;
   
    /////////////////        
   public JFrame oddzielnie;
   
   ////
    public MainGUI() {
       
   //     graf_jung = Przerob.daj_graf(start.ustaw.czyPlanarny,start.ustaw.wierzcholki,(float)(start.ustaw.gestosc));
        
        
        
        //////////
        initComponents(); 

        
      //oddzielnie=new JFrame();
       
       mysz = new DefaultModalGraphMouse();
       mysz.setMode(ModalGraphMouse.Mode.TRANSFORMING);
    //   myszmenu=mysz.getModeMenu();

 

       /////////////////////////////////
       
       //inf=new GrInfo();
       //inf.setAlwaysOnTop(true);
       ////////
       
       
       graf_jung = Przerob.daj_graf(false,1,(float)(1));
       oddzielnie=new JFrame();
       oddzielnie.setBounds(190,255,735,485);
       oddzielnie.setAlwaysOnTop(true);
       vv=Przerob.daj_panel(graf_jung, "kk",oddzielnie.getSize().width , oddzielnie.getSize().height-25);
       oddzielnie.add(vv);
       oddzielnie.setTitle("Widok na graf");
       oddzielnie.setForeground(Color.LIGHT_GRAY);
       oddzielnie.getContentPane().setBackground(Color.LIGHT_GRAY);
       oddzielnie.setVisible(true);
       
       ///
       
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane2 = new javax.swing.JLayeredPane();
        odGestosci = new javax.swing.JSlider();
        odMyszy = new javax.swing.JComboBox();
        czyszczenie = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        odLayoutu = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        odStartu = new javax.swing.JButton();
        odOprojekcie = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kolorowanie wierzchołków G.Bylina, T.Gajda, E.Wszołek 2013");
        setBackground(new java.awt.Color(147, 150, 171));
        setFocusCycleRoot(false);

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(64, 32, 153), 5), "Do grafu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(110, 20, 215))); // NOI18N

        odGestosci.setVisible(false);
        odGestosci.setFont(new java.awt.Font("DejaVu Sans", 0, 8)); // NOI18N
        odGestosci.setMajorTickSpacing(20);
        odGestosci.setMinorTickSpacing(10);
        odGestosci.setPaintLabels(true);
        odGestosci.setPaintTicks(true);
        odGestosci.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        odGestosci.setValueIsAdjusting(true);
        jLayeredPane2.add(odGestosci);
        odGestosci.setBounds(10, 320, 150, 41);
        odGestosci.getAccessibleContext().setAccessibleName("");
        odGestosci.getAccessibleContext().setAccessibleDescription("% szansy, że dowolny wierzchołek będzie połączony z innym wierzchołkiem");

        odMyszy.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Miejsca", "Przejścia", "Znakowanie", "Transforming", "Picking" }));
        odMyszy.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 38, 147), 2));
        odMyszy.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                odMyszyItemStateChanged(evt);
            }
        });
        odMyszy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odMyszyActionPerformed(evt);
            }
        });
        jLayeredPane2.add(odMyszy);
        odMyszy.setBounds(20, 40, 139, 24);

        czyszczenie.setBackground(new java.awt.Color(239, 208, 61));
        czyszczenie.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        czyszczenie.setForeground(new java.awt.Color(148, 146, 50));
        czyszczenie.setText("Wyczyść");
        czyszczenie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                czyszczenieActionPerformed(evt);
            }
        });
        jLayeredPane2.add(czyszczenie);
        czyszczenie.setBounds(20, 400, 140, 27);
        jLayeredPane2.add(jSeparator7);
        jSeparator7.setBounds(10, 120, 157, 14);

        odLayoutu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ISOM", "KK", "Circle", "Spring", "FR", "static(dla planarnych)" }));
        odLayoutu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 38, 147), 2));
        odLayoutu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        odLayoutu.setPreferredSize(new java.awt.Dimension(90, 30));
        odLayoutu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                odLayoutuItemStateChanged(evt);
            }
        });
        odLayoutu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odLayoutuActionPerformed(evt);
            }
        });
        jLayeredPane2.add(odLayoutu);
        odLayoutu.setBounds(20, 80, 139, 24);

        jLabel2.setText("Layout grafu:");
        jLayeredPane2.add(jLabel2);
        jLabel2.setBounds(20, 64, 140, 20);

        jLabel3.setText("Tryb myszy grafowej:");
        jLayeredPane2.add(jLabel3);
        jLabel3.setBounds(20, 26, 140, 14);

        jLayeredPane1.setBackground(javax.swing.UIManager.getDefaults().getColor("textHighlight"));
        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(19, 0, 239), 5), "Do algorytmów", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14), new java.awt.Color(110, 20, 215))); // NOI18N

        odStartu.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        odStartu.setBackground(Color.LIGHT_GRAY);
        odStartu.setText("START");
        odStartu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odStartuActionPerformed(evt);
            }
        });
        jLayeredPane1.add(odStartu);
        odStartu.setBounds(20, 490, 130, 30);

        odOprojekcie.setBackground(new java.awt.Color(177, 165, 108));
        odOprojekcie.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        odOprojekcie.setForeground(new java.awt.Color(1, 1, 1));
        odOprojekcie.setText("O projekcie");
        odOprojekcie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odOprojekcieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 729, Short.MAX_VALUE)
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(odOprojekcie, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(odOprojekcie, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void odStartuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odStartuActionPerformed

      
        // TODO add your handling code here:
    }//GEN-LAST:event_odStartuActionPerformed

    private void odOprojekcieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odOprojekcieActionPerformed

    
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_odOprojekcieActionPerformed

    private void odLayoutuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odLayoutuActionPerformed
        if (odLayoutu.getSelectedIndex()==0) {
            vv.setGraphLayout(new ISOMLayout(graf_jung));
            vv.repaint();
        } else if (odLayoutu.getSelectedIndex()==1) {
            vv.setGraphLayout(new KKLayout(graf_jung));
            vv.repaint();
        } else if (odLayoutu.getSelectedIndex()==2) {
            vv.setGraphLayout(new CircleLayout(graf_jung));
            vv.repaint();
        } else if (odLayoutu.getSelectedIndex()==3) {
            vv.setGraphLayout(new SpringLayout(graf_jung));
            vv.repaint();
        } else if (odLayoutu.getSelectedIndex()==4) {
            vv.setGraphLayout(new FRLayout(graf_jung));
            vv.repaint();
        } else if (odLayoutu.getSelectedIndex()==5) {
            vv.setGraphLayout(new StaticLayout<>(graf_jung, new lokator()));
            vv.repaint();
        }
    }//GEN-LAST:event_odLayoutuActionPerformed

    private void odLayoutuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_odLayoutuItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_odLayoutuItemStateChanged

    private void czyszczenieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_czyszczenieActionPerformed

        EdgeFactory.zeruj();
        CircVertexFactory.zeruj();
        odMyszy.setSelectedIndex(0);
        odLayoutu.setSelectedIndex(0);
        graf_jung = Przerob.daj_graf(true,0,(float)(0));
        oddzielnie.dispose();
        oddzielnie=new JFrame();
        oddzielnie.setBounds(190,255,735,485);
        oddzielnie.setTitle("Widok na graf");
        oddzielnie.setAlwaysOnTop(true);
        vv=Przerob.daj_panel(graf_jung, "kk",720,485-25);
        oddzielnie.add(vv);
        oddzielnie.setVisible(true);
    }//GEN-LAST:event_czyszczenieActionPerformed

    private void odMyszyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odMyszyActionPerformed

        switch((String)odMyszy.getSelectedItem())
        {
            case "Transforming":
            {
                mysz.setMode(ModalGraphMouse.Mode.TRANSFORMING);
                vv.setGraphMouse(mysz);
                vv.repaint();
                break;

            }
            case "Picking":
            {
                if (vv.getModel().getRelaxer()!=null){
                    vv.getModel().getRelaxer().stop();
                }
                mysz.setMode(ModalGraphMouse.Mode.PICKING);
                vv.setGraphMouse(mysz);
                vv.repaint();
                break;
            }
            case "Miejsca":
            {
                if (vv.getModel().getRelaxer()!=null){
                    vv.getModel().getRelaxer().stop();
                }

                PluggableGraphMouse myszka = new PluggableGraphMouse();
                myszka.add(new EditingGraphMousePlugin(new CircVertexFactory(), new EdgeFactory()));
                vv.setGraphMouse(myszka);
                vv.repaint();
                break;
            }
            case "Przejścia":
            {
                if (vv.getModel().getRelaxer()!=null){
                    vv.getModel().getRelaxer().stop();
                }

                PluggableGraphMouse myszka = new PluggableGraphMouse();
                myszka.add(new EditingGraphMousePlugin(new RectVertexFactory(), new EdgeFactory()));
                vv.setGraphMouse(myszka);
                vv.repaint();
                break;
            }
            case "Znakowanie":
            {
                vv.addGraphMouseListener(new GraphMouseListener(){
                    @Override
                    public void graphClicked(Object v, MouseEvent me) {
                        if (me.getButton() == MouseEvent.BUTTON1 && me.getClickCount() == 1) 
                        {
                            node clickedNode = (node) v;   
                            if(clickedNode.getShape()==nodeShape.CIRCLE) {
                                clickedNode.addMark();
                                vv.repaint();
                            }
                        }
                        me.consume(); 
                    }
                    @Override
                    public void graphPressed(Object v, MouseEvent me) {
                    }
                    @Override
                    public void graphReleased(Object v, MouseEvent me) {
                    }                   
                });
                break;
            }
        }
    }//GEN-LAST:event_odMyszyActionPerformed

    private void odMyszyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_odMyszyItemStateChanged

        // TODO add your handling code here:
    }//GEN-LAST:event_odMyszyItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton czyszczenie;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSlider odGestosci;
    private javax.swing.JComboBox odLayoutu;
    private javax.swing.JComboBox odMyszy;
    private javax.swing.JButton odOprojekcie;
    public javax.swing.JButton odStartu;
    // End of variables declaration//GEN-END:variables

    
}
