package smip;

import edu.uci.ics.jung.algorithms.layout.KKLayout;
import edu.uci.ics.jung.algorithms.layout.Layout;
import edu.uci.ics.jung.algorithms.layout.StaticLayout;
import edu.uci.ics.jung.visualization.VisualizationViewer;
import edu.uci.ics.jung.visualization.control.ModalGraphMouse;
import edu.uci.ics.jung.visualization.control.PluggableGraphMouse;
import edu.uci.ics.jung.visualization.decorators.ToStringLabeller;
import edu.uci.ics.jung.visualization.renderers.Renderer.VertexLabel.Position;

import model.Arc;
import model.MyVertex;
import model.PetriGraph;
import org.apache.commons.collections15.Factory;
import painter.MyVertexColorPainter;
import painter.MyVertexShapePainter;
import simulation.RunnableSimulationPetriGraph;
import smip.views.MatrixForm;
import smip.views.ReachabilityGraphForm;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.Arrays;
import java.util.Map;
import model.Place;
import model.factory.ArcFactory;
import model.factory.PlaceTransitionFactory;
import mouse.CheckingMouse.ArcChecker;
import mouse.CheckingMouse.EditingCheckingGraphMousePlugin;
import mouse.CheckingMouse.EditingModalGraphMouse2;
import mouse.CheckingMouse.MyVertexChecker;
import mouse.MousePlugin.SimulateGraphMousePlugin;
import org.apache.commons.collections15.Transformer;
import painter.BoundednessLabeller;
import painter.TransitionAlivenessColorPainter;
import smip.views.ShowGraph;

/**
 *
 * @author Elpidiusz
 */
public class PetriGraphGUI extends javax.swing.JFrame {

    public static PetriGraph graph;
    Factory<MyVertex> vertexFactory;
    Factory<Arc> edgeFactory;
    MyVertexChecker vCheck;
    ArcChecker eCheck;
    VisualizationViewer vv;
    Thread simulationThread;
    MatrixForm matrixForm;
    ReachabilityGraphForm reachabilityGraphForm;
    RunnableSimulationPetriGraph simulationPetriGraph;
    EditingModalGraphMouse2 gm;
    Properties properties;

    private SimulateGraphMousePlugin simulateGraphMousePlugin;

    /**
     * Creates new form PetriGraphGUI
     */
    public PetriGraphGUI() {
        initComponents();
        graph = new PetriGraph();
        vertexFactory = new PlaceTransitionFactory();
        edgeFactory = new ArcFactory();
        vCheck = new MyVertexChecker();
        eCheck = new ArcChecker();
        properties=new Properties(graph);
        setProperties();
        //pnlGraph.setSize(600, 400);
        Layout<MyVertex, Arc> layout = new StaticLayout(graph);
        layout.setSize(this.pnlGraph.getSize());

        vv = new VisualizationViewer<>(layout);
        vv.setPreferredSize(this.pnlGraph.getSize());
        // Show vertex and edge labels
        vv.getRenderContext().setVertexLabelTransformer(new ToStringLabeller());
        vv.getRenderContext().setEdgeLabelTransformer(new ToStringLabeller());
        vv.getRenderContext().setLabelOffset(20);
        vv.getRenderContext().setVertexFillPaintTransformer(new MyVertexColorPainter());
        vv.getRenderContext().setVertexShapeTransformer(new MyVertexShapePainter());
        // Create a graph mouse and add it to the visualization viewer

        EditingCheckingGraphMousePlugin plugin = new EditingCheckingGraphMousePlugin(vertexFactory,
                edgeFactory);
        plugin.setProperites(properties);

        gm = new EditingModalGraphMouse2(vv.getRenderContext(), vertexFactory, edgeFactory);
        gm.remove(gm.getEditingPlugin());

        plugin.setVertexChecker(vCheck);
        plugin.setEdgeChecker(eCheck);

        gm.setEditingPlugin(plugin);
        vv.setGraphMouse(gm);

        createMenu(gm);
        gm.setMode(ModalGraphMouse.Mode.EDITING);
        simulationPetriGraph = new RunnableSimulationPetriGraph(graph, vv);
        vv.setBackground(new java.awt.Color(204, 255, 255));

        pnlGraph.add(vv);
        pnlGraph.validate();
        pnlGraph.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGraph = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlActions = new javax.swing.JPanel();
        btnIncidenceMatrix = new javax.swing.JButton();
        btnReachabilityGraph = new javax.swing.JButton();
        btnCoverabilityGraph = new javax.swing.JButton();
        tgbtnBoundednessPlaces = new javax.swing.JToggleButton();
        tgbtnL1TransitionsLiveness = new javax.swing.JToggleButton();
        chkRefresh = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblActivity = new javax.swing.JLabel();
        lblBoundedness = new javax.swing.JLabel();
        lblConservation = new javax.swing.JLabel();
        lblReversibility = new javax.swing.JLabel();
        lblL1Liveness = new javax.swing.JLabel();
        lblL4Liveness = new javax.swing.JLabel();
        pnlSimulation = new javax.swing.JPanel();
        chkIsSelectionByUser = new javax.swing.JCheckBox();
        lblDelayVal = new javax.swing.JLabel();
        tbnSimulate = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        sldDeley = new javax.swing.JSlider();
        spnSteps = new javax.swing.JSpinner();
        tbnStep = new javax.swing.JToggleButton();
        menuBar = new javax.swing.JMenuBar();
        elmAbout = new javax.swing.JMenu();
        mitAuthors = new javax.swing.JMenuItem();
        mitLicence = new javax.swing.JMenuItem();
        elmNet = new javax.swing.JMenu();
        mitSaveNet = new javax.swing.JMenuItem();
        mitLoadNet = new javax.swing.JMenuItem();
        mitClearNet = new javax.swing.JMenuItem();
        elmViews = new javax.swing.JMenu();
        mitMatrix = new javax.swing.JMenuItem();
        mitOsi = new javax.swing.JMenuItem();
        mitPokrycia = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sieć miejsc i przejsć");
        setName("main_frame"); // NOI18N

        pnlGraph.setToolTipText("Panel z grafem");
        pnlGraph.setPreferredSize(new java.awt.Dimension(600, 457));
        pnlGraph.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                pnlGraphComponentResized(evt);
            }
        });

        pnlActions.setToolTipText("Panel z akcjami do wykonania na grafie");
        pnlActions.setPreferredSize(new java.awt.Dimension(112, 400));

        btnIncidenceMatrix.setLabel("M. wejść,wyjść, incydecji");
        btnIncidenceMatrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncidenceMatrixActionPerformed(evt);
            }
        });

        btnReachabilityGraph.setText("Graf osiągalności");
        btnReachabilityGraph.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReachabilityGraphMouseClicked(evt);
            }
        });
        btnReachabilityGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReachabilityGraphActionPerformed(evt);
            }
        });

        btnCoverabilityGraph.setText("Graf pokrycia");
        btnCoverabilityGraph.setToolTipText("prawie graf osiągalności");
        btnCoverabilityGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoverabilityGraphActionPerformed(evt);
            }
        });

        tgbtnBoundednessPlaces.setText("Ograniczoność miejsc");
        tgbtnBoundednessPlaces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgbtnBoundednessPlacesActionPerformed(evt);
            }
        });
        tgbtnBoundednessPlaces.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tgbtnBoundednessPlacesPropertyChange(evt);
            }
        });

        tgbtnL1TransitionsLiveness.setText("L1-żywotność miejsc");
        tgbtnL1TransitionsLiveness.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgbtnL1TransitionsLivenessActionPerformed(evt);
            }
        });

        chkRefresh.setSelected(true);
        chkRefresh.setText("odświeżaj");
        chkRefresh.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkRefreshStateChanged(evt);
            }
        });

        jLabel2.setText("Aktywność:");

        jLabel3.setText("Ograniczoność:");

        jLabel4.setText("Zachowawczość:");

        jLabel5.setText("Odwracalność:");

        jLabel6.setText("Żywotność L1:");

        jLabel7.setText("Żywotność L4:");

        lblActivity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblActivity.setText("-");

        lblBoundedness.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblBoundedness.setText("-");

        lblConservation.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblConservation.setText("-");

        lblReversibility.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblReversibility.setText("-");

        lblL1Liveness.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblL1Liveness.setText("-");

        lblL4Liveness.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblL4Liveness.setText("-");

        javax.swing.GroupLayout pnlActionsLayout = new javax.swing.GroupLayout(pnlActions);
        pnlActions.setLayout(pnlActionsLayout);
        pnlActionsLayout.setHorizontalGroup(
            pnlActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tgbtnL1TransitionsLiveness, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnIncidenceMatrix, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReachabilityGraph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCoverabilityGraph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tgbtnBoundednessPlaces, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlActionsLayout.createSequentialGroup()
                        .addGroup(pnlActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(0, 124, Short.MAX_VALUE)
                        .addGroup(pnlActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblActivity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblBoundedness, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlActionsLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblReversibility))
                    .addGroup(pnlActionsLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblL1Liveness))
                    .addGroup(pnlActionsLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblL4Liveness))
                    .addGroup(pnlActionsLayout.createSequentialGroup()
                        .addComponent(chkRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlActionsLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblConservation)))
                .addContainerGap())
        );
        pnlActionsLayout.setVerticalGroup(
            pnlActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlActionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chkRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblActivity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblBoundedness))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblConservation))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblReversibility))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblL1Liveness))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlActionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblL4Liveness))
                .addGap(122, 122, 122)
                .addComponent(btnIncidenceMatrix)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReachabilityGraph)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCoverabilityGraph)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tgbtnBoundednessPlaces)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tgbtnL1TransitionsLiveness)
                .addGap(29, 29, 29))
        );

        btnIncidenceMatrix.getAccessibleContext().setAccessibleName("M. wejść,wyjść, incydecji");

        jTabbedPane1.addTab("Właściwości", pnlActions);

        chkIsSelectionByUser.setText("Możliwość wyboru przejścia");
        chkIsSelectionByUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkIsSelectionByUserActionPerformed(evt);
            }
        });

        lblDelayVal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblDelayVal.setText("1000 ms");

        tbnSimulate.setText("Symuluj ∞");
        tbnSimulate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnSimulateActionPerformed(evt);
            }
        });

        jLabel1.setText("Opóźnienie:");

        sldDeley.setMajorTickSpacing(200);
        sldDeley.setMaximum(1200);
        sldDeley.setMinimum(100);
        sldDeley.setMinorTickSpacing(100);
        sldDeley.setPaintTicks(true);
        sldDeley.setSnapToTicks(true);
        sldDeley.setValue(1000);
        sldDeley.setPreferredSize(new java.awt.Dimension(50, 23));
        sldDeley.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldDeleyStateChanged(evt);
            }
        });

        spnSteps.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));
        spnSteps.setValue(1);

        tbnStep.setText("Krok →");
        tbnStep.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tbnStepStateChanged(evt);
            }
        });
        tbnStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnStepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSimulationLayout = new javax.swing.GroupLayout(pnlSimulation);
        pnlSimulation.setLayout(pnlSimulationLayout);
        pnlSimulationLayout.setHorizontalGroup(
            pnlSimulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSimulationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSimulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSimulationLayout.createSequentialGroup()
                        .addComponent(tbnSimulate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(pnlSimulationLayout.createSequentialGroup()
                        .addGroup(pnlSimulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sldDeley, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlSimulationLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblDelayVal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlSimulationLayout.createSequentialGroup()
                                .addComponent(spnSteps, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tbnStep)))
                        .addGap(9, 9, 9))
                    .addGroup(pnlSimulationLayout.createSequentialGroup()
                        .addComponent(chkIsSelectionByUser)
                        .addContainerGap(55, Short.MAX_VALUE))))
        );
        pnlSimulationLayout.setVerticalGroup(
            pnlSimulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSimulationLayout.createSequentialGroup()
                .addContainerGap(273, Short.MAX_VALUE)
                .addComponent(chkIsSelectionByUser)
                .addGap(18, 18, 18)
                .addGroup(pnlSimulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblDelayVal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sldDeley, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tbnSimulate)
                .addGap(4, 4, 4)
                .addGroup(pnlSimulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnSteps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbnStep))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Symulacja", pnlSimulation);

        elmAbout.setText("O programie");

        mitAuthors.setText("Autorzy");
        mitAuthors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitAuthorsActionPerformed(evt);
            }
        });
        elmAbout.add(mitAuthors);

        mitLicence.setText("Licencja");
        elmAbout.add(mitLicence);

        menuBar.add(elmAbout);

        elmNet.setText("Sieć");

        mitSaveNet.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        mitSaveNet.setText("Zapisz sieć");
        mitSaveNet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitSaveNetActionPerformed(evt);
            }
        });
        elmNet.add(mitSaveNet);

        mitLoadNet.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        mitLoadNet.setText("Wczytaj sieć");
        mitLoadNet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitLoadNetActionPerformed(evt);
            }
        });
        elmNet.add(mitLoadNet);

        mitClearNet.setText("Wyczyść");
        mitClearNet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitClearNetActionPerformed(evt);
            }
        });
        elmNet.add(mitClearNet);

        menuBar.add(elmNet);

        elmViews.setText("Widok");

        mitMatrix.setText("Macierz");
        mitMatrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitMatrixActionPerformed(evt);
            }
        });
        elmViews.add(mitMatrix);

        mitOsi.setText("Osiągalność");
        mitOsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitOsiActionPerformed(evt);
            }
        });
        elmViews.add(mitOsi);

        mitPokrycia.setText("Pokrycie");
        elmViews.add(mitPokrycia);

        menuBar.add(elmViews);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlGraph, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlGraph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void setProperties(){
        properties.setLblActivity(lblActivity);
        properties.setLblBoundedness(lblBoundedness);
        properties.setLblConservation(lblConservation);
        properties.setLblL1Liveness(lblL1Liveness);
        properties.setLblL4Liveness(lblL4Liveness);
        properties.setLblReversibility(lblReversibility);
    }
    private void createMenu(EditingModalGraphMouse2 gm) {
        JMenu modeMenu = gm.getModeMenu();
        modeMenu.setText("Mouse Mode");
        modeMenu.setIcon(null);
        modeMenu.setPreferredSize(new Dimension(80, 20));
        menuBar.add(modeMenu);
    }

    private void blockOptions(boolean doWeBlock) {
        btnIncidenceMatrix.setEnabled(!doWeBlock);
        btnReachabilityGraph.setEnabled(!doWeBlock);
        btnCoverabilityGraph.setEnabled(!doWeBlock);
        elmNet.setEnabled(!doWeBlock);
        elmViews.setEnabled(!doWeBlock);
        chkIsSelectionByUser.setEnabled(!doWeBlock);
        tgbtnBoundednessPlaces.setEnabled(!doWeBlock);
        tbnSimulate.setEnabled(!doWeBlock);
        tbnStep.setEnabled(!doWeBlock);
        tgbtnL1TransitionsLiveness.setEnabled(!doWeBlock);
    }

    private void drawTables(int[][] inc, int[][] nPlus, int[][] nMinus) {
        if (matrixForm == null) {
            matrixForm = new MatrixForm();
        }

        matrixForm.setVisible(true);
        if (inc == null || inc.length == 0 || inc[0].length == 0) {
            return;
        }
        matrixForm.drawInc(inc, graph.getTransitionSet(), graph.getPlaceSet());
        matrixForm.drawNplus(nPlus, graph.getTransitionSet(), graph.getPlaceSet());
        matrixForm.drawNminus(nMinus, graph.getTransitionSet(), graph.getPlaceSet());

    }


    private void tbnSimulateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnSimulateActionPerformed
        if (tbnSimulate.isSelected()) {
            startSimulate(-1, tbnSimulate);
        } else {
            stopSimulate();
        }
    }//GEN-LAST:event_tbnSimulateActionPerformed

    private void mitAuthorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitAuthorsActionPerformed

        JDialog authors = new JDialog(this, "Autorzy");
        authors.setSize(200, 100);
        JTextArea engineers = new JTextArea("pan inżynier Elpidiusz Wszołek \n"
                + "pan inżynier Tomasz Gajda\n"
                + "pan inżynier Piotr Knop\n"
                + "pan inżynier Grzegorz Bylina");
        engineers.setEditable(false);
        engineers.setBackground(Color.LIGHT_GRAY);
        authors.add(engineers);
        authors.setAlwaysOnTop(true);
        authors.setVisible(true);
    }//GEN-LAST:event_mitAuthorsActionPerformed

    private void mitSaveNetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitSaveNetActionPerformed
        //new SaveLoadGui('s').setVisible(true);
        JFrame parentFrame = new JFrame();

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Wybierz gdzie zapisać");
        fileChooser.setSelectedFile(new File("PetriNet"));

        int userSelection = fileChooser.showSaveDialog(parentFrame);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            System.out.println("Save as file: " + fileToSave.getAbsolutePath());
            FileOutputStream fos = null;
            ObjectOutputStream oos = null;
            try {
                fos = new FileOutputStream(fileToSave);
                oos = new ObjectOutputStream(fos);

                oos.writeObject(this.graph); //serializacja obiektu
            } catch (FileNotFoundException e) {
                e.printStackTrace();
            } catch (IOException e) {
                e.printStackTrace();
            } finally {
                try {
                    if (oos != null) {
                        oos.close();
                    }
                } catch (IOException e) {
                }
                try {
                    if (fos != null) {
                        fos.close();
                    }
                } catch (IOException e) {
                }
            }
        }
    }//GEN-LAST:event_mitSaveNetActionPerformed

    private void mitLoadNetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitLoadNetActionPerformed
        //new SaveLoadGui('l').setVisible(true);
        JFrame parentFrame = new JFrame();

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Wybierz skąd wczytać plik");
        //fileChooser.setSelectedFile(new File(txtFileName.getText()));

        int userSelection = fileChooser.showOpenDialog(parentFrame);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToOpen = fileChooser.getSelectedFile();
            System.out.println("Read from file: " + fileToOpen.getAbsolutePath());
            System.out.println(graph.toString());
            try {
                FileInputStream fileIn = new FileInputStream(fileToOpen);
                ObjectInputStream in = new ObjectInputStream(fileIn);
                this.graph = (PetriGraph) in.readObject();
                vv.setGraphLayout(new KKLayout(graph));
                in.close();
                fileIn.close();
            } catch (IOException i) {
                i.printStackTrace();
                return;
            } catch (ClassNotFoundException c) {
                System.out.println("PetriNet class not found");
                c.printStackTrace();
                return;
            }
        }
    }//GEN-LAST:event_mitLoadNetActionPerformed

    private void mitMatrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitMatrixActionPerformed
        drawTables(null, null, null);
    }//GEN-LAST:event_mitMatrixActionPerformed

    private void sldDeleyStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldDeleyStateChanged
        lblDelayVal.setText(Integer.toString(sldDeley.getValue()) + " ms");
        simulationPetriGraph.setDelay(sldDeley.getValue());
    }//GEN-LAST:event_sldDeleyStateChanged

    private void drawRechabilityGrap() {
        if (reachabilityGraphForm == null) {
            reachabilityGraphForm = new ReachabilityGraphForm();
        }

        reachabilityGraphForm.setVisible(true);
        reachabilityGraphForm.calculateReachabilityGraph(graph);
    }

    private void mitOsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitOsiActionPerformed
        drawRechabilityGrap();
    }//GEN-LAST:event_mitOsiActionPerformed

    private void chkIsSelectionByUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkIsSelectionByUserActionPerformed

    }//GEN-LAST:event_chkIsSelectionByUserActionPerformed

    private void mitClearNetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitClearNetActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_mitClearNetActionPerformed

    private void startSimulate(int param, JToggleButton button) {
        blockOptions(true);
        button.setEnabled(true);
        simulationPetriGraph.setTransitionPerStep(param);
        simulationPetriGraph.setButton(button);
        if (!chkIsSelectionByUser.isSelected()) {
            simulationThread = new Thread(simulationPetriGraph);
            simulationThread.start();
        } else {
            PluggableGraphMouse simulationGraphMouse = new PluggableGraphMouse();
            simulationGraphMouse.add(simulateGraphMousePlugin);
            vv.setGraphMouse(simulationGraphMouse);
        }
    }

    private void stopSimulate() {
        blockOptions(false);

        if (!chkIsSelectionByUser.isSelected()) {
            simulationThread.interrupt();
        } else {
            chkIsSelectionByUser.setEnabled(true);
            vv.setGraphMouse(gm);
        }
    }

    private void tbnStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnStepActionPerformed
        if (tbnStep.isSelected()) {
            startSimulate((int) spnSteps.getValue() - 1, tbnStep);
        } else {
            stopSimulate();
        }
    }//GEN-LAST:event_tbnStepActionPerformed

    private void pnlGraphComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pnlGraphComponentResized
        if (vv != null) {
            vv.setPreferredSize(this.pnlGraph.getSize());
        }
    }//GEN-LAST:event_pnlGraphComponentResized

    private void tbnStepStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tbnStepStateChanged
        if (!tbnStep.isSelected()&& simulationThread!=null) {
            stopSimulate();
        }
    }//GEN-LAST:event_tbnStepStateChanged

    private void tgbtnL1TransitionsLivenessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgbtnL1TransitionsLivenessActionPerformed
        if (this.tgbtnL1TransitionsLiveness.isSelected()) {
            blockOptions(true);
            tgbtnL1TransitionsLiveness.setEnabled(true);
            graph.calculateAndSetGraphL1Liveness();
            vv.getRenderContext().setVertexFillPaintTransformer(new TransitionAlivenessColorPainter());
            vv.repaint();
        } else {
            blockOptions(false);
            vv.getRenderContext().setVertexFillPaintTransformer(new MyVertexColorPainter());
            vv.repaint();
        }
    }//GEN-LAST:event_tgbtnL1TransitionsLivenessActionPerformed

    private void tgbtnBoundednessPlacesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tgbtnBoundednessPlacesPropertyChange

    }//GEN-LAST:event_tgbtnBoundednessPlacesPropertyChange

    private void tgbtnBoundednessPlacesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgbtnBoundednessPlacesActionPerformed
        if (this.tgbtnBoundednessPlaces.isSelected()) {
            blockOptions(true);
            tgbtnBoundednessPlaces.setEnabled(true);
            graph.calculateAndSetPlacesBoundedness();
            vv.getRenderContext().setVertexLabelTransformer(new BoundednessLabeller());
            vv.getRenderer().getVertexLabelRenderer().setPosition(Position.CNTR);
            vv.repaint();
        } else {
            blockOptions(false);
            vv.getRenderContext().setVertexLabelTransformer(new ToStringLabeller());
            vv.getRenderer().getVertexLabelRenderer().setPosition(Position.AUTO);
            vv.repaint();
        }
    }//GEN-LAST:event_tgbtnBoundednessPlacesActionPerformed

    private void btnCoverabilityGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoverabilityGraphActionPerformed
        Transformer<Map<Place, Integer>, String> vlt = new Transformer<Map<Place, Integer>, String>() {
            public String transform(Map<Place, Integer> map) {
                String label = "";
                Place[] places = map.keySet().toArray(new Place[map.keySet().size()]);
                Arrays.sort(places);
                for (Place p : places) {
                    label += "," +/*Integer.toString(p.getId())+":"+*/ ((map.get(p) == -1) ? "∞ " : map.get(p));
                }
                return label.substring(1);
            }
        };
        ShowGraph.showRCGraph(this.graph.getCoverabilityGraph(), vlt, "Graf pokrycia", 500, 300);
    }//GEN-LAST:event_btnCoverabilityGraphActionPerformed

    private void btnReachabilityGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReachabilityGraphActionPerformed
        drawRechabilityGrap();
    }//GEN-LAST:event_btnReachabilityGraphActionPerformed

    private void btnReachabilityGraphMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReachabilityGraphMouseClicked
        if (evt.getButton() == MouseEvent.BUTTON3) {
            Transformer<Map<Place, Integer>, String> vlt = (Map<Place, Integer> map) -> {
                String label = "";
                Place[] places = map.keySet().toArray(new Place[map.keySet().size()]);
                Arrays.sort(places);
                for (Place p : places) {
                    label += "," + map.get(p);
                }
                return label.substring(1);
            };
            ShowGraph.showRCGraph(this.graph.getReachabilityGraph(), vlt, "Graf osiągalności", 500, 300);
        }
    }//GEN-LAST:event_btnReachabilityGraphMouseClicked

    private void btnIncidenceMatrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncidenceMatrixActionPerformed
        drawTables(graph.getNincidence(), graph.getNplus(), graph.getNminus());
    }//GEN-LAST:event_btnIncidenceMatrixActionPerformed

    private void chkRefreshStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkRefreshStateChanged
       if(properties!=null){
           properties.setRefresh(chkRefresh.isSelected());
           properties.refreshProperties();
       }
    }//GEN-LAST:event_chkRefreshStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PetriGraphGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PetriGraphGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PetriGraphGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PetriGraphGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PetriGraphGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCoverabilityGraph;
    private javax.swing.JButton btnIncidenceMatrix;
    private javax.swing.JButton btnReachabilityGraph;
    private javax.swing.JCheckBox chkIsSelectionByUser;
    private javax.swing.JCheckBox chkRefresh;
    private javax.swing.JMenu elmAbout;
    private javax.swing.JMenu elmNet;
    private javax.swing.JMenu elmViews;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblActivity;
    private javax.swing.JLabel lblBoundedness;
    private javax.swing.JLabel lblConservation;
    private javax.swing.JLabel lblDelayVal;
    private javax.swing.JLabel lblL1Liveness;
    private javax.swing.JLabel lblL4Liveness;
    private javax.swing.JLabel lblReversibility;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mitAuthors;
    private javax.swing.JMenuItem mitClearNet;
    private javax.swing.JMenuItem mitLicence;
    private javax.swing.JMenuItem mitLoadNet;
    private javax.swing.JMenuItem mitMatrix;
    private javax.swing.JMenuItem mitOsi;
    private javax.swing.JMenuItem mitPokrycia;
    private javax.swing.JMenuItem mitSaveNet;
    private javax.swing.JPanel pnlActions;
    private javax.swing.JPanel pnlGraph;
    private javax.swing.JPanel pnlSimulation;
    private javax.swing.JSlider sldDeley;
    private javax.swing.JSpinner spnSteps;
    private javax.swing.JToggleButton tbnSimulate;
    private javax.swing.JToggleButton tbnStep;
    private javax.swing.JToggleButton tgbtnBoundednessPlaces;
    private javax.swing.JToggleButton tgbtnL1TransitionsLiveness;
    // End of variables declaration//GEN-END:variables
}
