/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smip;

import trash.SMiP;
import Struktura_jung.SaveNetUtil;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JLabel;

/**
 * @author Grzesiek
 */
public class SaveLoadGui extends javax.swing.JFrame {

    /**
     * Creates new form SaveLoadGui
     */
    public SaveLoadGui(char operation) {
        initComponents();
        switch(operation)
        {
            case 's':
                fileChooser.setDialogType(JFileChooser.SAVE_DIALOG);
                break;
            case 'l':
                fileChooser.setDialogType(JFileChooser.OPEN_DIALOG);
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        fileChooser.setApproveButtonText("");
        fileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(fileChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooserActionPerformed
       try{
            if(fileChooser.getDialogType()==JFileChooser.OPEN_DIALOG){
                SaveNetUtil.loadNet(fileChooser.getSelectedFile().getAbsolutePath());
            }
            else{
                SaveNetUtil.saveNet(fileChooser.getSelectedFile().getAbsolutePath());
            }
        }catch(Exception e){
           JDialog panieInzynierze = new JDialog(SMiP.mainGUI,"Panie inżynierze");
           panieInzynierze.setSize(300, 200);
           panieInzynierze.setLocation(500, 500);
           panieInzynierze.add(new JLabel("Wystąpił problem natury informatycznej, panie inżynierze"));
           panieInzynierze.setAlwaysOnTop(true);
           panieInzynierze.setVisible(true);
           e.printStackTrace();
        }
        finally{
           this.dispose();
        }
    }//GEN-LAST:event_fileChooserActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser fileChooser;
    // End of variables declaration//GEN-END:variables
}
